export const UPDATE_REQUEST_ENDTIME = 'UPDATE_REQUEST_ENDTIME';
export const UDPATE_REQUEST_STARTTIME = 'UPDATE_REQUEST_STARTTIME';
export const SET_LAST_REQUEST_URL = 'SET_LAST_REQUEST_URL';
export const TOGGLE_IS_REQUESTING = 'TOGGLE_IS_REQUESTING';

