export const SET_REQUEST_ERROR = 'SET_REQUEST_ERROR';
export const ADD_MESSAGE_TO_HISTORY = 'ADD_MESSAGE_TO_HISTORY';

export const UPDATE_REQUEST_ENDTIME = 'UPDATE_REQUEST_ENDTIME';
export const UPDATE_REQUEST_STARTTIME = 'UPDATE_REQUEST_STARTTIME';
export const SET_LAST_REQUEST_URL = 'SET_LAST_REQUEST_URL';
export const TOGGLE_IS_REQUESTING = 'TOGGLE_IS_REQUESTING';
export const SET_LAST_REQUEST_TIME = 'SET_LAST_REQUEST_TIME';

export const SET_RESPONSE_IS_SUCCESSFUL = 'SET_RESPONSE_IS_SUCCESSFUL';

export const SET_EARTHQUAKE_METADATA = 'SET_RAW_EARTHQUAKE_METADATA';
export const SET_FLATTENED_EARTHQUAKE_DATA = 'SET_FLATTENED_EARTHQUAKE_DATA';
export const SET_EARTHQUAKES_SORTED_BY_MAGNITUDE = 'SET_EARTHQUAKES_SORTED_BY_MAGNITUDE';

export const TOGGLE_OVERVIEW_CAN_RENDER = 'TOGGLE_OVERVIEW_CAN_RENDER';
export const SET_TOP_FIVE_MAGNITUDE_EARTHQUAKES = 'SET_TOP_FIVE_MAGNITUDE_EARTHQUAKES';

